---
title: "Open Educational Resources"
---

My main outputs are open educational materials for teaching data skills, research methods, and statistics. 

## PsyTeachR

At the University of Glasgow, I am a core member of [PsyTeachR](https://psyteachr.github.io/){target="_blank"} - an initiative to teach reproducible data analysis to psychology students (and beyond). We teach R/RStudio across all of our degrees, from first-year undergraduates to specialist MSc students. If you are interested in using these materials or want to discuss teaching R/RStudio to psychology students, please get in touch! The main resources I have contributed to are:

- [Fundamentals of Quantitative Analysis](https://psyteachr.github.io/quant-fun-v3/){target="_blank"} by Bartlett and Toivo. We use this to teach data wrangling, visualisation, and analysis to MSc Psychology Conversion students.

- [Statistics and Research Design](https://psyteachr.github.io/statsres-v2/){target="_blank"} by Bartlett, Rousselet, and DeBruine. We use this to teach advanced statistical techniques from general linear regression to Bayesian statistics to specialist MSc students.

- [RSetGo](https://psyteachr.github.io/RSetGo/){target="_blank"}. This is mainly aimed at University of Glasgow students, but this guide walks through installing R/RStudio for Windows and Mac.

## Dissemination using Quarto and Github Pages

I wrote this guide - [Dissemination using Quarto and Github Pages](https://bartlettje.github.io/dissemination_quarto/){target="_blank"} - to demonstrate how you can combine Quarto and Github pages to help disseminate your work. This is mainly aimed at researchers and covers reproducible presentations, online books, and blogs/websites. I made this website using the techniques I demonstrate in the book if you want to see what's possible! 

## Introduction to Power Analysis

One of my most popular open educational resources is a beginners guide demonstrating how to perform a power analysis using different software. You can download the guide on the [Open Science Framework](https://osf.io/zqphw/){target="_blank"}. It currently covers:

- Some background on the statistics and rationale behind power analysis

- Power analysis using G*Power

- Power analysis using jamovi

- Power analysis for factorial designs using the SuperPower app

If you use the guide, please cite it as: Bartlett, J.E. (2022, May 3). Introduction to Power Analysis: A Guide to G*Power, jamovi, and Superpower. https://osf.io/zqphw/. DOI: 10.17605/OSF.IO/PCFVJ.

Last updated: **03/05/2022**.

We also adapted the guide for a peer-reviewed article focusing on introducing power analysis using jamovi: **Bartlett, J. E.** & Charles, S. J. (2022). Power to the People: A Beginner’s Tutorial to Power Analysis using jamovi. [*Meta Psychology*](https://open.lnu.se/index.php/metapsychology/article/view/3078){target="_blank"}, 6, 1-20.

## ScholaRship

With my colleagues from the University of Glasgow and University of Edinburgh, we have started writing a series of tutorials on using R for the scholarship of teaching and learning. We recognised many resources out there either do not focus on scholarship research or do not use realistic messy data you could expect when working with student data. We are steadily building the book as a resource and my contributions have currently been: 

- [Introduction](https://emilynordmann.github.io/scholaRship/intro.html){target="_blank"} - Here we outline the motiviation behind our book and what knowledge we expect to engage with the book. 

- [Creating synthetic datasets](https://emilynordmann.github.io/scholaRship/creating-synthetic-datasets.html){target="_blank"} - I led on our first substantive chapter to demonstrate creating synthetic data sets when ethics concerns might limit sharing data from participants. Previous tutorials were highly technical or focused on topics researchers in the scholarship of teaching and learning might not resonate with, so we wanted to write an accessible introduction. 

## OSF preregistration R Markdown template

When I preregister a study, my favourite template to use was the OSF preregistration challenge. Now that the challenge has finished, the COS have created an updated template. When you select a template on the OSF, there is the option to include an R script to demonstrate something like a power analysis or planned analysis. I thought it would be a good idea to streamline this process and combine the preregistration template with the power of R.

I created a .Rmd file with the OSF preregistration template headers and information. Now you can write your preregistration using R Markdown and provide any code and output directly, making it fully reproducible. You can download the template here on my [Github page](files/OSF preregistration template.Rmd){target="_blank"}.

For an example of how it can be used, you can find the preregistration for one of my studies on the OSF. The final knitted version of the document is available as a [PDF](https://osf.io/hjk5u/){target="_blank"} for easy reading, and the [.Rmd file](https://osf.io/fqs6j/){target="_blank"} is available for reproducibility. You can also find a [YouTube](https://youtu.be/VdhtdsKtac0){target="_blank"} video of a workshop I presented demonstrating how you can use the template for preregistration.

## Creating Experiments Using OpenSesame Guide

I wrote a guide on how to create cognitive tasks in OpenSesame. It is aimed at absolute beginners and includes minimal code. There are currently three tasks included: the Stroop task, Eriksen Flanker task, and a Go NoGo task with images. The guide and images for the third task are available on my [OSF](https://osf.io/tm3z2/){target="_blank"} project page for cognitive tasks.

I built several experiments using OpenSesame and PsychoPy for my PhD and for undergraduates to use in their dissertations. You may find it useful to adapt one of the cognitive tasks I have built for your own research. You can download them from the [OSF](https://osf.io/awjcn/){target="_blank"}.  

Last updated: **27/02/2019**.

The current list of available tasks is:

- Go-NoGo Task (OpenSesame)

- Eriksen Flanker Task (OpenSesame)

- Dot Probe Task (OpenSesame and PsychoPy)

- Anti-Saccade Task (PsychoPy)

## Introduction to JASP guide

I wrote a guide to transition students from using SPSS to JASP. You can access both the [guide](https://osf.io/p2hzg/){target="_blank"} and the [data sets](https://osf.io/7x8hj/){target="_blank"} I used for the examples on the Open Science Framework. The sourcing of the data sets are credited to Kevin McIntyre who made them available on the [Open Stats Lab](https://sites.trinity.edu/osl){target="_blank"}.

The guide currently covers the following topics:

- How to navigate around JASP

- Getting basic descriptive statistics and plots

- Assessing parametric assumptions

- Conducting independent and paired samples T-Tests

- Calculating the correlation between two variables

- One-way repeated measures and independent samples ANOVA

- Bayesian paired samples T-Test

Last updated: **14/03/2018**.