---
title: "Workshops and Talks"
---

## Workshops

I run workshops based on my open educational materials, from an introduction to R/RStudio for wrangling, visualisation, and analysis, to demonstrating how to create open education materials. I am always up for running workshops, so please reach out if you are interested! We can discuss costs depending on the budget you have available.

### Dissemination using Quarto and Github Pages

I have run workshops from 1-3 hours for creating open educational materials and reproducible presentations using Quarto and Github using my [Dissemination using Quarto and Github Pages](https://bartlettje.github.io/dissemination_quarto/){target="_blank"} guide.

Past workshops:

-   UK Conference on Teaching Statistics, Glasgow, 25/06/2025.

-   Software Upskilling for Researchers, University of Glasgow, 28/03/2025.

-   School of Psychology and Neuroscience, University of Glasgow, 28/06/2024.

### Introduction to R for Researchers

In this one-day workshop, I introduce researchers to using R/RStudio for reproducible data analysis. We establish all the key data skills from writing reproducible documents, visualising data, wrangling data, and performing a basic code review. For a preview, you can see the materials online: [Introduction to R for Researchers](https://bartlettje.github.io/Intro_R_Researchers/){target="_blank"}.

Past workshops:

-   York St John University, York, 03/07/2025.

### APA-style manuscripts with RMarkdown and papaja demonstration

I have delivered workshops on using papaja ([Aust & Barth, 2022](https://github.com/crsh/papaja){target="_blank"}) to create reproducible APA-style manuscripts. When you download the template, it is easy to see how you complete the YAML, but as a template, the bulk of the manuscript is blank. Therefore, I created a mock example using just a few packages to show how you can use it for your own study. You can access the workshop slides and mock example files [here on my Github repo](https://github.com/BartlettJE/papaja_demo){target="_blank"}.

Past workshops:

-   Software Upskilling for Researchers, University of Glasgow, 28/03/2025.

-   Methods and Metascience discussion group, University of Glasgow, 16/09/2024.

### Introduction to data visualisation using R/RStudio

Together with Wil Toivo, we ran an introduction to data visualisation using R/RStudio for PhD students at the SGSSS summer school. We adapted a guide from colleagues in our department to develop an [online book](https://wtoivo.github.io/SGSSS-data-viz-workshop/){target="_blank"} for the workshop. We introduce students to R/RStudio, data visualisation principles, and used pair programming as an effective way of structuring the session.

Past workshops:

-   SGSSS Summer School, Dundee, 05/06/2024.

-   SGSSS Summer School, Edinburgh, 08/06/2023.

-   SGSSS Summer School, Edinburgh, 16/06/2022.

## Talks

The following section is an overview of conference talks I have delivered, with links to the materials where possible.

### 2025

-   **Bartlett, J. E.** Rapidly teaching programming and reproducible research practices. Edinburgh Winter Programming School, Edinburgh.

### 2024

-   **Bartlett, J. E.** The two Rs: Teaching regression in psychology and neuroscience through reproducibility and replicability. UK Conference on Teaching Statistics, Manchester.

### 2023

-   **Bartlett, J. E.** & Charles, S.C. Make null results great again: A tutorial of equivalence testing. Learning, Teaching, and Scholarship Conference, University of Glasgow, Glasgow.

### 2022

-   **Bartlett, J. E.** & Charles, S.J. A Beginner’s Tutorial to Power Analysis using jamovi. Open Science Community Rotterdam. Slides available on the [OSF](https://osf.io/zrcuh/){target="_blank"}.

-   Paterson, H. & **Bartlett, J. E.** #psyTeachR: Teaching Robust and Reproducible Research Methods. Teaching Statistics in R Symposium, Nottingham Trent University, UK.

### 2021

-   **Bartlett, J. E.** Optimising preregistration using data simulation. PsyPAG Simulation Summer School. Recording available on [YouTube](https://youtu.be/VdhtdsKtac0){target="_blank"}.

-   **Bartlett, J.E.** Learning the hard way: Reproducible workflows. Riot Science Club, University of Wolverhampton. Slides available on the [OSF](https://osf.io/zk4dj/){target="_blank"} and recording available on [YouTube](https://youtu.be/P5F_aVz3J70){target="_blank"}.

-   **Bartlett, J.E.** Power to the People: Introduction to Power Analysis. University of Wolverhampton.

### 2020

-   **Bartlett, J.E.** Power to the People: Introduction to Power Analysis. Russian Academy of Education. Slides available on the [OSF](https://osf.io/68mcq/){target="_blank"} and recording available on [YouTube](https://youtu.be/uj9Ces3jbmc){target="_blank"}.

### 2019

-   **Bartlett, J.E.** Emptying the File Drawer: Attentional Bias in Daily and Non-Daily Smokers. Society for the Study of Addiction (SSA) PhD Symposium, Newcastle. Presentation available on the [OSF](https://osf.io/43wrn/){target="_blank"}.

### 2018

-   **Bartlett, J.E.** An Introduction and Practical Guide to Open Science Practices in Psychology. Workshop delivered at PsyPAG 2018, University of Hudderfield, UK. Presentation and materials available on the [OSF](https://osf.io/w82ms/){target="_blank"}.

### 2017

-   **Bartlett, J. E.**, Jenks, R. A., Wilson, N. E., Farias, M. and Wright, H. Light Smokers Fixate their Attention on Smoking Cues. Health and Life Sciences Postgraduate Research Symposium, Coventry University. Available from [figshare.](https://figshare.com/articles/Bartlett-J-HLS_conference_pdf/4929659){target="_blank"}.

### 2016

-   **Bartlett, J. E.**, Jenks, R. A., Wilson, N.E, Farias, M. Attentional Bias in Light and Heavy Smokers. Oral presentation at the PsyPAG annual conference, University of York, UK. Available from [figshare.](https://figshare.com/articles/PsyPag_2016_presentation_Attentional_bias_in_light_and_heavy_smokers/3501641){target="_blank"}.

-   **Bartlett, J. E.**, Jenks, R. A., Wilson, N.E, Farias, M. The Differences in Smoking Habits, Motives, and Attentional Bias in Nicotine Dependent and Non-Dependent Smokers. Poster presentation at the British Association for Psychopharmacology summer meeting, Brighton, UK. Available from [figshare.](https://figshare.com/articles/The_difference_in_smoking_habits_motives_and_attentional_bias_in_nicotine_dependent_and_non-dependent_smokers/3420847){target="_blank"}.

### 2015

-   **Bartlett, J. E.**, Jenks, R. A., Wilson, N.E, Farias, M. The Differences in Smoking Habits, Motives, and Attentional Bias in Nicotine Dependent and Non-Dependent Smokers. BPS Psychobiology Section Annual Scientific Meeting, Windermere UK. Available from [figshare.](https://figshare.com/articles/Attentional_Bias_in_Nicotine_Dependent_and_Non_Dependent_Smokers/3188959){target="_blank"}.
